from . import res_partner
from . import submission_integrations
from . import submission
from . import product_template
from . import import_products_wizard
from . import image_upload_wizard
from . import sale_order_line
from . import migration_wizard
from . import submission_label
from . import submission_rejected_line
from . import brand
from . import res_users
from . import res_config_settings
